### ISSUE TITLE
Модуль LiqPay

### ISSUE THREAD

**Issue by OCappLab** [BroCart/BroCart-MULTISTORE-v3.x#3]
Нет желания вставить модуль LiqPay с использованием их самого последнего API?
А то та версия, какая в OpenCart, если мне память не изменяет еще с версии 1.4 тянется.
Сейчас самая последняя версия 3

**Comment by BroCart** [comment]
Здравствуйте, да, можно занятся интеграцией на последнюю версию, но чуть позже, сейчас основное время на создание торговой площадки уходит, спасибо за исправления и корректировку, нам это очень важно !

**Comment by OCappLab** [comment]
Могу я написать, тем более есть наработки уже. Единственное нужно будет только протестить

**Comment by BroCart** [comment]
Тестировщики есть, код перед заливкой на гитхаб тестим на отдельном домене, все баги описываем сразу в ветке: https://forum.brocart.net/forums/brocart-bug-report

**Comment by OCappLab** [comment]
Ок, принял.
Тогда напишу и сделаю Пулл, или как у Вас заведено, просто файлы передать?

**Comment by BroCart** [comment]
Можно через пулл, но желательно отдельным архивом, если не затруднит, то вот электронка: 
partner@brocart.net или в скайпе можем продолжить сотрудничать: live:artur.coder_1

**Comment by OCappLab** [comment]
У меня скайпа нет, на почту тогда пришлю.

**Comment by OCappLab** [comment]
Отправил на почту
